name: Run Python Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'    # Runs every 5 minutes
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Run the script
      run: python main.py
